//2.1.1
// s.push(23);s.push(56);b=s.pop();a=s.pop();s.push(a-b);s.push(3);b=s.pop();a=s.pop();s.push(a*b);
// s.push(1);s.push(3);s.push(4);b=s.pop();a=s.pop();s.push(a/b);b=s.pop();a=s.pop();s.push(a+b);b=s.pop();
// a=s.pop();s.push(a/b);

//2.1.2
//s.push(2);s.push(4);s.push(7);s.push(32);b=s.pop();a=s.pop();s.push(a/b);......................
//...
//....